version: '3.7'
networks:
  net1:

services:
  cassandra:
    image: "cassandra-4-agent:latest"
    container_name: cassandra
    networks: [ "net1" ]
    environment:
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "DS_LICENSE=accept"
      - "CASSANDRA_DC=datacenter1"
      - "DC=datacenter1"
      - "LOCAL_JMX=no"
      - "JVM_EXTRA_OPTS=-javaagent:/agent-c4-2.0.0-all.jar=pulsarServiceUrl=pulsar://pulsar:6650,cdcWorkingDir=/var/lib/cassandra/cdc,pulsarBatchDelayInMs=100 -javaagent:/jmx_prometheus_javaagent-0.16.1.jar=8081:/jmx_prometheus_exporter.yaml -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=7199"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - "9042:9042"
      - "7199:7199"
      - "8081:8081"

  cassandra-stress:
    image: "vroyer/cassandra-stress:latest"
    networks: [ "net1" ]
    environment:
      - "JVM_OPTS=-Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=5001 -Dcom.sun.management.jmxremote.port=5001 -javaagent:/jmx_prometheus_javaagent-0.16.1.jar=8082:/jmx_exporter_config.yaml"
    command: [ "user", "profile=/table1.yaml", "no-warmup", "ops(insert=1)", "n=100000000", "-rate", "threads=1", "-node", "cassandra", "-jmx"]

  pulsar:
    image: "datastax/lunastreaming-all:2.10_0.2"
    container_name: pulsar
    networks: [ "net1" ]
    environment:
      - "PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    ports:
      - '8080:8080'
      - '6650:6650'
    command: /bin/bash -c "bin/pulsar standalone -nss"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
    container_name: elasticsearch
    networks: [ "net1" ]
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    #volumes:
    #  - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks: [ "net1" ]
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./build/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks: [ "net1" ]
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./build/grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
