tenant: public
namespace: default
name: cassandra-source-ks1-table1
destination-topic-name: data-ks1.table1
configs:
  keyspace: ks1
  table: table1
  events.topic: persistent://public/default/events-ks1.table1
  events.subscription.name: source-sub-table1
  contactPoints: cassandra
  loadBalancing.localDc: datacenter1