{
 "title": "CDC Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cassandra Source Connector CQL query latency",
   "type": "timeseries",
   "description": "CQL query latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(pulsar_source_user_metric__sum{metric=\"query_latency\"}[1m])/increase(pulsar_source_user_metric__count{metric=\"query_latency\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source Connector replication latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(pulsar_source_user_metric__sum{metric=\"replication_latency\"}[1m])/increase(pulsar_source_user_metric__count{metric=\"replication_latency\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Source Connector cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pulsar_source_user_metric__sum{metric=\"cache_size\"}[1m])/increase(pulsar_source_user_metric__count{metric=\"cache_size\"}[1m])",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Cassandra Source Connector CQL query executors",
   "type": "timeseries",
   "description": "CQL query executors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pulsar_source_user_metric__sum{metric=\"query_executors\"}[1m])/increase(pulsar_source_user_metric__count{metric=\"query_executors\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CdcAgent SentMutations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cassandra_cdcagent_sentmutations",
     "legendFormat": "cassandra_cdcagent_sentmutations"
    }
   ]
  },
  {
   "title": "CDC disk space usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cassandra_commitlog_totalcdccommitlogsizeinbytes",
     "legendFormat": "cassandra_commitlog_totalcdccommitlogsizeinbytes"
    },
    {
     "expr": "cassandra_commitlog_totalcdcspacesizeinbytes",
     "legendFormat": "cassandra_commitlog_totalcdcspacesizeinbytes"
    }
   ]
  },
  {
   "title": "Cassandra-Stress requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (job)(rate(cassandra_stress_requests[1m]))",
     "legendFormat": "cassandra_stress_requests"
    }
   ]
  },
  {
   "title": "Pulsar Topics Rate In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "pulsar_rate_in{topic=\"persistent://public/default/events-ks1.table1\"}",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "pulsar_rate_in{topic=\"persistent://public/default/data-ks1.table1\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "CDC Agent tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "cassandra_threadpools_pendingtasks{threadpools=\"CdcCommitlogProcessor\"}",
     "legendFormat": "{{threadpools}}"
    },
    {
     "expr": "cassandra_cdcagent_maxsubmittedtasks",
     "legendFormat": "cassandra_cdcagent_maxsubmittedtasks"
    }
   ]
  }
 ]
}